/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qpcTo6ejVNU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Gabarito } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function HomePage() {
  return (
    (<div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 md:px-8 lg:px-10">
        <div className="container mx-auto flex items-center justify-between">
          <Link
            href="#"
            className="flex items-center gap-2 font-semibold text-lg"
            prefetch={false}>
            <BrainIcon className="w-6 h-6" />
            <span>ipai.me</span>
          </Link>
          <nav className="hidden md:flex items-center gap-6">
            <Link href="#" className="hover:underline" prefetch={false}>
              About
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Services
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Contact
            </Link>
          </nav>
          <Button variant="secondary" className="hidden md:inline-flex">
            Get Started
          </Button>
          <Button variant="outline" size="icon" className="md:hidden">
            <MenuIcon className="w-6 h-6" />
            <span className="sr-only">Toggle Menu</span>
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section className="bg-primary py-16 md:py-24 lg:py-32">
          <div className="container mx-auto px-6 md:px-8 lg:px-10 text-center">
            <h1
              className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tight text-primary-foreground">
              Unlock the Power of AI for Your Business
            </h1>
            <p
              className="mt-4 max-w-3xl mx-auto text-lg md:text-xl text-primary-foreground/80">
              Our AI-powered services help you streamline operations, boost productivity, and drive innovation. From
              personal assistants to competitive gaming coaching, we&apos;ve got you covered.
            </p>
            <div className="mt-8 flex justify-center gap-4">
              <Button variant="secondary" className="px-8 py-3">
                Explore Services
              </Button>
              <Button variant="outline" className="px-8 py-3">
                Schedule a Demo
              </Button>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-24">
          <div className="container mx-auto px-6 md:px-8 lg:px-10">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <div className="bg-muted rounded-lg p-6 flex flex-col gap-4">
                <div className="flex items-center gap-4">
                  <BotIcon className="w-10 h-10 text-primary" />
                  <h3 className="text-xl font-semibold">Personal Assistants</h3>
                </div>
                <p className="text-muted-foreground">
                  Leverage AI to create personalized virtual assistants that streamline your workflows and boost
                  productivity. Powered by D-ID.
                </p>
                <Link href="https://chat.d-id.com/" className="mt-auto" prefetch={false}>
                  Learn More
                  <ArrowRightIcon className="ml-2 w-4 h-4" />
                </Link>
              </div>
              <div className="bg-muted rounded-lg p-6 flex flex-col gap-4">
                <div className="flex items-center gap-4">
                  <BriefcaseIcon className="w-10 h-10 text-primary" />
                  <h3 className="text-xl font-semibold">AI Coaching</h3>
                </div>
                <p className="text-muted-foreground">
                  Empower your employees with AI-driven coaching for training, development, and competitive gaming.
                </p>
                <Link href="https://escapevelocity.vercel.app/" className="mt-auto" prefetch={false}>
                  Learn More
                  <ArrowRightIcon className="ml-2 w-4 h-4" />
                </Link>
              </div>
              <div className="bg-muted rounded-lg p-6 flex flex-col gap-4">
                <div className="flex items-center gap-4">
                  <LightbulbIcon className="w-10 h-10 text-primary" />
                  <h3 className="text-xl font-semibold">Idea Validator</h3>
                </div>
                <p className="text-muted-foreground">
                  Unleash your creativity with our idea novelty checker for IP, patents, research papers, grants, and
                  bids.
                </p>
                <Link href="#" className="mt-auto" prefetch={false}>
                  Learn More
                  <ArrowRightIcon className="ml-2 w-4 h-4" />
                </Link>
              </div>
              <div className="bg-muted rounded-lg p-6 flex flex-col gap-4">
                <div className="flex items-center gap-4">
                  <InfoIcon className="w-10 h-10 text-primary" />
                  <h3 className="text-xl font-semibold">Data Extraction</h3>
                </div>
                <p className="text-muted-foreground">
                  Unlock valuable insights with our data extraction and analysis services to identify high-net-worth
                  individuals and investment patterns.
                </p>
                <Link href="#" className="mt-auto" prefetch={false}>
                  Learn More
                  <ArrowRightIcon className="ml-2 w-4 h-4" />
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-16 lg:py-24">
          <div className="container mx-auto px-6 md:px-8 lg:px-10">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div>
                <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold">Research-Backed Approach</h2>
                <p className="mt-4 text-muted-foreground">
                  At ipai.me, we pride ourselves on our research-driven methodology. Our team of experts meticulously
                  analyzes data and industry trends to develop innovative solutions that deliver tangible results for
                  our clients.
                </p>
                <div className="mt-6">
                  <Button className="px-8 py-3">Learn More</Button>
                </div>
              </div>
              <div>
                <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold">Money-Back Guarantee</h2>
                <p className="mt-4 text-muted-foreground">
                  We stand behind the quality of our services. If you&apos;re not completely satisfied with the results, we
                  offer a 100% money- back guarantee. Our commitment to your success is unwavering.
                </p>
                <div className="mt-6">
                  <Button className="px-8 py-3">Learn More</Button>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-24">
          <div className="container mx-auto px-6 md:px-8 lg:px-10">
            <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold text-center">Hear from Our Clients</h2>
            <div className="mt-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <div className="bg-muted rounded-lg p-6 flex flex-col gap-4">
                <div className="flex items-center gap-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-semibold">John Doe</div>
                    <div className="text-muted-foreground text-sm">CEO, Acme Inc.</div>
                  </div>
                </div>
                <p className="text-muted-foreground">
                  &quot;The AI-powered services from ipai.me have been a game-changer for our business. We&apos;ve seen
                  a significant boost in productivity and innovation.&quot;
                </p>
              </div>
              <div className="bg-muted rounded-lg p-6 flex flex-col gap-4">
                <div className="flex items-center gap-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-semibold">Jane Smith</div>
                    <div className="text-muted-foreground text-sm">CTO, Globex Inc.</div>
                  </div>
                </div>
                <p className="text-muted-foreground">
                  &quot;The data extraction and analysis services from ipai.me have been invaluable in helping us
                  identify investment patterns, coaching methods and recommendations.&quot;
                </p>
              </div>
              <div className="bg-muted rounded-lg p-6 flex flex-col gap-4">
                <div className="flex items-center gap-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-semibold">Michael Johnson</div>
                    <div className="text-muted-foreground text-sm">R&D Manager, Stark Industries</div>
                  </div>
                </div>
                <p className="text-muted-foreground">
                  &quot;The AI coaching and idea generation services from ipai.me have been instrumental in
                  driving innovation and employee development within our organization.&quot;
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted text-muted-foreground py-8 md:py-12">
        <div className="container mx-auto px-6 md:px-8 lg:px-10">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            <div className="flex flex-col gap-2">
              <h4 className="font-semibold">Company</h4>
              <Link href="#" className="hover:underline" prefetch={false}>
                About
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Team
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Careers
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Contact
              </Link>
            </div>
            <div className="flex flex-col gap-2">
              <h4 className="font-semibold">Services</h4>
              <Link href="#" className="hover:underline" prefetch={false}>
                Personal Assistants
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                AI Coaching
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Idea Validator
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Data Extraction
              </Link>
            </div>
            <div className="flex flex-col gap-2">
              <h4 className="font-semibold">Resources</h4>
              <Link href="#" className="hover:underline" prefetch={false}>
                Blog
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Case Studies
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                FAQ
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Documentation
              </Link>
            </div>
            <div className="flex flex-col gap-2">
              <h4 className="font-semibold">Legal</h4>
              <Link href="#" className="hover:underline" prefetch={false}>
                Privacy Policy
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Terms of Service
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Cookie Policy
              </Link>
            </div>
          </div>
          <div className="mt-8 text-center text-sm">&copy; 2024 ipai.me. All rights reserved.</div>
        </div>
      </footer>
    </div>)
  );
}

function ArrowRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>)
  );
}


function BotIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M12 8V4H8" />
      <rect width="16" height="12" x="4" y="8" rx="2" />
      <path d="M2 14h2" />
      <path d="M20 14h2" />
      <path d="M15 13v2" />
      <path d="M9 13v2" />
    </svg>)
  );
}


function BrainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z" />
      <path
        d="M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z" />
      <path d="M15 13a4.5 4.5 0 0 1-3-4 4.5 4.5 0 0 1-3 4" />
      <path d="M17.599 6.5a3 3 0 0 0 .399-1.375" />
      <path d="M6.003 5.125A3 3 0 0 0 6.401 6.5" />
      <path d="M3.477 10.896a4 4 0 0 1 .585-.396" />
      <path d="M19.938 10.5a4 4 0 0 1 .585.396" />
      <path d="M6 18a4 4 0 0 1-1.967-.516" />
      <path d="M19.967 17.484A4 4 0 0 1 18 18" />
    </svg>)
  );
}


function BriefcaseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>)
  );
}


function InfoIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>)
  );
}


function LightbulbIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5" />
      <path d="M9 18h6" />
      <path d="M10 22h4" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}
